package com.example.demo.entities;
// Generated Jul 12, 2019 12:21:46 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CargaAcademica generated by hbm2java
 */
@Entity
@Table(name = "carga_academica", catalog = "cargaprojectbd")
public class CargaAcademica implements java.io.Serializable {

	private int idCargaAcademica;
	private Curso curso;
	private Docente docente;
	private String semestre;
	
	private String nombre;
	private long horas;
	
	@Transient
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Transient
	public long getHoras() {
		return horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	public CargaAcademica() {
	}

	public CargaAcademica(int idCargaAcademica, Curso curso, Docente docente) {
		this.idCargaAcademica = idCargaAcademica;
		this.curso = curso;
		this.docente = docente;
	}

	public CargaAcademica(int idCargaAcademica, Curso curso, Docente docente, String semestre) {
		this.idCargaAcademica = idCargaAcademica;
		this.curso = curso;
		this.docente = docente;
		this.semestre = semestre;
	}
	
	public CargaAcademica(String nombre, long horas, String semestre) {
		this.nombre = nombre;
		this.horas = horas;
		this.semestre = semestre;
	}

	@Id

	@Column(name = "id_carga_academica", unique = true, nullable = false)
	public int getIdCargaAcademica() {
		return this.idCargaAcademica;
	}

	public void setIdCargaAcademica(int idCargaAcademica) {
		this.idCargaAcademica = idCargaAcademica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_curso", nullable = false)
	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_docente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "semestre", length = 50)
	public String getSemestre() {
		return this.semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

}
