package com.example.demo.entities;
// Generated Jul 12, 2019 12:21:46 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", catalog = "cargaprojectbd")
public class Curso implements java.io.Serializable {

	private int idCurso;
	private String nombre;
	private Integer HSemanales;
	private Set<CargaAcademica> cargaAcademicas = new HashSet<CargaAcademica>(0);

	public Curso() {
	}

	public Curso(int idCurso, String nombre) {
		this.idCurso = idCurso;
		this.nombre = nombre;
	}

	public Curso(int idCurso, String nombre, Integer HSemanales, Set<CargaAcademica> cargaAcademicas) {
		this.idCurso = idCurso;
		this.nombre = nombre;
		this.HSemanales = HSemanales;
		this.cargaAcademicas = cargaAcademicas;
	}

	@Id

	@Column(name = "id_curso", unique = true, nullable = false)
	public int getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(int idCurso) {
		this.idCurso = idCurso;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "h_semanales")
	public Integer getHSemanales() {
		return this.HSemanales;
	}

	public void setHSemanales(Integer HSemanales) {
		this.HSemanales = HSemanales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
	public Set<CargaAcademica> getCargaAcademicas() {
		return this.cargaAcademicas;
	}

	public void setCargaAcademicas(Set<CargaAcademica> cargaAcademicas) {
		this.cargaAcademicas = cargaAcademicas;
	}

}
